version: '3.8'

services:
  # 1. Backend Service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: toko-sembako-backend
    dns:
      - 192.168.1.1
    ports:
      - "127.0.0.1:8000:7860" # Hanya diakses via local / Caddy untuk keamanan
    environment:
      # Koneksi database Supabase
      - DATABASE_URL=postgresql://postgres.thtfwypskzknwgbzdrvv:Ivalpermana%5D@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
    restart: always

  # 2. Frontend Service (Vue 3 PWA)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # API URL diatur relatif (/api) agar frontend dan backend berkomunikasi
        # di domain yang sama lewat Caddy/Ngrok
        - VITE_API_URL=/api
    container_name: toko-sembako-frontend
    ports:
      - "127.0.0.1:8080:80" # Hanya diakses via local / Caddy
    restart: always
    depends_on:
      - backend

  # 3. Caddy Service (Reverse Proxy & Routing Internal)
  caddy:
    image: caddy:2-alpine
    container_name: toko-sembako-caddy
    restart: always
    dns:
      - 192.168.1.1
    ports:
      - "127.0.0.1:80:80" # Diikat ke localhost karena traffic dari luar masuk lewat tunnel Ngrok
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  # 4. Ngrok Tunnel Service (Menghubungkan Server Lokal ke Internet Bebas Blokir ISP)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: toko-sembako-ngrok
    restart: always
    dns:
      - 192.168.1.1
    environment:
      - NGROK_AUTHTOKEN=3E24uTY7VKHHJjCg9pEEoVl4cg3_4mkqbv7MGSn6JswRt1kCW # Token Ngrok Anda
    command:
      - http
      - caddy:80
      - --domain=granular-sinuous-falsify.ngrok-free.dev
    depends_on:
      - caddy

volumes:
  caddy_data:
  caddy_config:
